### ISSUE TITLE
Create API for web view to request the user's location

### ISSUE THREAD

**Issue by tupakapoor** [TheHolyGrail/Zoot#35]
A web view requesting a user's location via JavaScript will prompt the user for permission every time the location is requested.

It would be convenient to use the native OS's location so that permission is only requested once and passed into the webview via a js callback.

**Comment by bsneed** [comment]
Thanks @tupakapoor.  I think that's a great addition.

@angelodipaolo this is outside of the scope of the other work we're doing, but would be a nice add in the near future.

**Comment by angelodipaolo** [comment]
:+1: great idea
