### ISSUE TITLE
Dismissing the modal "See more stores" during checkout causes blank screen.

### ISSUE THREAD

**Issue by dpettigrew** [TheHolyGrail/Zoot#48]
After the “See more stores” seems like sometimes I get just white screen with a nav bar and other times I get back to the checkout but the tab bar has reappeared.
This is on “Done” button tap from the modal after picking a store.

**Comment by bsneed** [comment]
Please don't file Walmart bugs in Zoot unless they've been narrowed down to specifics that leave out Walmart details.  Use the internal JIRA to assign to angelo or whoever appropriate.
